import Link from 'next/link'

export const metadata = { title: 'Terms of Service — MechIQ' }

const prose: React.CSSProperties = {
  color: '#8892a4', lineHeight: 1.8, fontSize: '0.95rem', marginBottom: '20px',
}
const h2style: React.CSSProperties = {
  color: '#e8eaf0', fontWeight: 700, fontSize: '1.15rem',
  marginTop: '36px', marginBottom: '10px',
}

export default function TermsPage() {
  return (
    <div style={{ background: '#0d0f14', minHeight: '100vh', fontFamily: "'Segoe UI', system-ui, sans-serif" }}>
      <nav style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 5%', height: '64px',
        background: 'rgba(13,15,20,0.92)', borderBottom: '1px solid #2a3040',
      }}>
        <Link href="/" style={{ fontSize: '1.4rem', fontWeight: 800, letterSpacing: '-0.5px', color: '#f59e0b', textDecoration: 'none' }}>
          Mech<span style={{ color: '#e8eaf0' }}>IQ</span>
        </Link>
      </nav>

      <div style={{ maxWidth: '720px', margin: '0 auto', padding: '60px 5% 80px' }}>
        <h1 style={{ color: '#e8eaf0', fontWeight: 800, fontSize: 'clamp(1.8rem, 4vw, 2.4rem)', letterSpacing: '-0.8px', marginBottom: '8px' }}>
          Terms of Service
        </h1>
        <p style={{ color: '#4a5568', fontSize: '0.85rem', marginBottom: '40px' }}>
          Last updated: 11 May 2026 · Operated by Athena Ventures Ltd, United Kingdom
        </p>

        <p style={prose}>
          These Terms of Service ("Terms") govern your use of MechIQ ("the Service"), operated by Athena Ventures Ltd. By creating an account you agree to these Terms.
        </p>

        <h2 style={h2style}>1. The Service</h2>
        <p style={prose}>
          MechIQ provides AI-assisted technical information for automotive professionals. Responses are generated by large language models and are provided for informational purposes only. They do not constitute professional engineering advice. You are solely responsible for any decisions or actions taken based on information provided by the Service.
        </p>

        <h2 style={h2style}>2. Eligibility</h2>
        <p style={prose}>
          You must be at least 18 years old and a resident of the United Kingdom to use MechIQ. By registering you confirm that this is the case.
        </p>

        <h2 style={h2style}>3. Subscriptions and billing</h2>
        <p style={prose}>
          Paid plans are billed monthly in advance in GBP. All prices include VAT where applicable. Subscriptions renew automatically unless cancelled. You may cancel at any time via your dashboard; cancellation takes effect at the end of the current billing period. Refunds are provided at our discretion and are not available for partial months.
        </p>

        <h2 style={h2style}>4. Fair use</h2>
        <p style={prose}>
          Free accounts are limited to 5 queries per day. Paid plans are subject to reasonable fair use limits. We reserve the right to throttle or suspend accounts that generate unusually high query volumes or that use the Service in an automated or non-human manner.
        </p>

        <h2 style={h2style}>5. Acceptable use</h2>
        <p style={prose}>
          You must not use the Service to generate content that is unlawful, harmful, or misleading; to attempt to extract training data or reverse-engineer AI models; to resell or sublicense access to the Service; or in any way that violates applicable UK law.
        </p>

        <h2 style={h2style}>6. Intellectual property</h2>
        <p style={prose}>
          The MechIQ platform, branding, and underlying software are owned by Athena Ventures Ltd. AI-generated responses are provided to you for your own professional use. You may not republish or commercialise response content without our written permission.
        </p>

        <h2 style={h2style}>7. Limitation of liability</h2>
        <p style={prose}>
          To the maximum extent permitted by UK law, Athena Ventures Ltd is not liable for any indirect, incidental, or consequential damages arising from use of the Service or reliance on AI-generated content. Our total liability to you in any 12-month period shall not exceed the total subscription fees paid by you in that period.
        </p>

        <h2 style={h2style}>8. Changes to these Terms</h2>
        <p style={prose}>
          We may update these Terms from time to time. We will notify registered users by email at least 14 days before material changes take effect. Continued use of the Service after that date constitutes acceptance of the revised Terms.
        </p>

        <h2 style={h2style}>9. Governing law</h2>
        <p style={prose}>
          These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
        </p>

        <h2 style={h2style}>10. Contact</h2>
        <p style={prose}>
          Athena Ventures Ltd · <a href="mailto:hello@mechiq.co.uk" style={{ color: '#f59e0b' }}>hello@mechiq.co.uk</a>
        </p>

        <div style={{ marginTop: '48px', paddingTop: '24px', borderTop: '1px solid #2a3040' }}>
          <Link href="/" style={{ color: '#f59e0b', textDecoration: 'none', fontSize: '0.9rem' }}>← Back to MechIQ</Link>
          <span style={{ color: '#2a3040', margin: '0 12px' }}>·</span>
          <Link href="/privacy" style={{ color: '#8892a4', textDecoration: 'none', fontSize: '0.9rem' }}>Privacy Policy</Link>
        </div>
      </div>
    </div>
  )
}
